[package]
name = "rust_tokenizers"
version = "6.2.4"
authors = ["Guillaume Becquin <guillaume.becquin@gmail.com>"]
edition = "2018"
description = "High performance tokenizers for Rust"
repository = "https://github.com/guillaume-be/rust-tokenizers"
license = "Apache-2.0"
readme = "README.md"
build = "build.rs"
keywords = ["nlp", "machine-learning", "tokenizer"]

[dependencies]
csv = "1.1.6"
unicode-normalization = "0.1.17"
rayon = "1.5.0"
lazy_static = "1.4.0"
itertools = "0.10.0"
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.64"
regex = "1.4.5"
protobuf = "= 2.22.1"
hashbrown = "0.9.1"
unicode-normalization-alignments = "0.1.12"
thiserror = "1.0.24"

[dev-dependencies]
tempfile = "3.2.0"
dirs = "3.0.1"
reqwest = {version = "0.11.2", features = ["blocking"]}
anyhow = "1.0.38"

[build-dependencies]
protobuf-codegen-pure = {version = "2.22.1", optional = true}

[features]
proto-compile = [ "protobuf-codegen-pure" ]

[lib]
name = "rust_tokenizers"
path = "src/lib.rs"
crate-type = ["lib"]
