[package]
name = "rust_tokenizers"
version = "7.0.0"
authors = ["Guillaume Becquin <guillaume.becquin@gmail.com>"]
edition = "2018"
description = "High performance tokenizers for Rust"
repository = "https://github.com/guillaume-be/rust-tokenizers"
license = "Apache-2.0"
readme = "README.md"
build = "build.rs"
keywords = ["nlp", "machine-learning", "tokenizer"]

[dependencies]
csv = "1.1.6"
unicode-normalization = "0.1.19"
rayon = "1.5.1"
lazy_static = "1.4.0"
itertools = "0.10.1"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.69"
regex = "1.5.4"
protobuf = "= 2.23.0"
hashbrown = "0.11.2"
unicode-normalization-alignments = "0.1.12"
thiserror = "1.0.30"

[dev-dependencies]
tempfile = "3.2.0"
dirs = "4.0.0"
reqwest = {version = "0.11.6", features = ["blocking"]}
anyhow = "1.0.45"

[build-dependencies]
protobuf-codegen-pure = {version = "2.23.0", optional = true}

[features]
proto-compile = [ "protobuf-codegen-pure" ]

[lib]
name = "rust_tokenizers"
path = "src/lib.rs"
crate-type = ["lib"]
