[package]
name = "rust_tokenizers"
version = "6.0.0"
authors = ["Guillaume Becquin <guillaume.becquin@gmail.com>"]
edition = "2018"
description = "High performance tokenizers for Rust"
repository = "https://github.com/guillaume-be/rust-tokenizers"
license = "Apache-2.0"
readme = "README.md"
build = "build.rs"
keywords = ["nlp", "machine-learning", "tokenizer"]

[dependencies]
csv = "1.1.3"
unicode-normalization = "0.1.13"
rayon = "1.4.1"
lazy_static = "1.4.0"
itertools = "0.9.0"
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
regex = "1.4.1"
protobuf = "= 2.18.0"
hashbrown = "0.9.1"
unicode-normalization-alignments = "0.1.12"
thiserror = "1.0.21"

[dev-dependencies]
tempfile = "3.1.0"
dirs = "3.0.1"
reqwest = {version = "0.10.8", features = ["blocking"]}
anyhow = "1.0.33"

[build-dependencies]
protobuf-codegen-pure = {version = "2.18.0", optional = true}

[features]
proto-compile = [ "protobuf-codegen-pure" ]

[lib]
name = "rust_tokenizers"
path = "src/lib.rs"
crate-type = ["lib"]
